# Generated by Django 2.2.1 on 2020-02-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0002_remove_movie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='photo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
