# Generated by Django 2.2.1 on 2020-02-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0005_auto_20200204_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cookie',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
