# Generated by Django 2.2.1 on 2020-02-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0008_cities_films_info_presentation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='names',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='informations',
            new_name='presentation',
        ),
        migrations.RenameField(
            model_name='presentation',
            old_name='dates',
            new_name='film',
        ),
    ]
