# Generated by Django 2.2.1 on 2020-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0009_auto_20200204_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='city',
        ),
        migrations.AddField(
            model_name='films',
            name='city',
            field=models.ManyToManyField(to='movieapi.Cities'),
        ),
    ]
