# Generated by Django 2.2.1 on 2020-02-04 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0010_auto_20200204_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='city',
        ),
        migrations.AddField(
            model_name='films',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movieapi.Cities'),
        ),
    ]
