# Generated by Django 2.2.1 on 2020-02-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0011_auto_20200204_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='city',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='movieapi.Cities'),
        ),
    ]
