# Generated by Django 2.2.1 on 2020-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0013_auto_20200204_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='city',
        ),
        migrations.RemoveField(
            model_name='info',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='film',
        ),
        migrations.AddField(
            model_name='films',
            name='cityfilms',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cityfilms', to='movieapi.Cities'),
        ),
        migrations.AddField(
            model_name='info',
            name='presentationinfo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='presentationinfo', to='movieapi.Presentation'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='filmpresentation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='filmpresentation', to='movieapi.Films'),
        ),
    ]
