# Generated by Django 2.2.1 on 2020-02-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0014_auto_20200204_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='cityfilms',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='cityfilms', to='movieapi.Cities'),
        ),
        migrations.AlterField(
            model_name='info',
            name='presentationinfo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='presentationinfo', to='movieapi.Presentation'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='filmpresentation',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='filmpresentation', to='movieapi.Films'),
        ),
    ]
