# Generated by Django 2.2.1 on 2020-02-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0003_auto_20200204_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('id_film', models.IntegerField(blank=True, default=0)),
                ('photo', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='presentation_info',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='film_presentation',
        ),
        migrations.AddField(
            model_name='info',
            name='informations',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='movieapi.Presentation'),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.DeleteModel(
            name='Films',
        ),
        migrations.AddField(
            model_name='film',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='movieapi.City'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presentations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='movieapi.Film'),
            preserve_default=False,
        ),
    ]
