# Generated by Django 2.2.1 on 2020-02-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_auto_20200204_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='films',
            new_name='city_film',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='informations',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='presentation',
            old_name='presentations',
            new_name='film_presentations',
        ),
    ]
