# Generated by Django 2.2.1 on 2020-02-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0006_city_cookie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info',
            new_name='info_presen',
        ),
    ]
